# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2.1

# Simple CircleCI configuration for testing builds
# Original config backed up to config.yml.original

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.5
    resource_class: large
    steps:
      - checkout

      - restore_cache:
          keys:
            - maven-dependencies-{{ checksum "pom.xml" }}
            - maven-dependencies-

      - run:
          name: Create Maven settings
          command: |
            mkdir -p ~/.m2
            cat > ~/.m2/settings.xml << 'EOF'
            <?xml version="1.0" encoding="UTF-8"?>
            <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                          http://maven.apache.org/xsd/settings-1.0.0.xsd">
              <profiles>
                <profile>
                  <id>default</id>
                  <repositories>
                    <repository>
                      <id>central</id>
                      <url>https://repo.maven.apache.org/maven2</url>
                      <releases>
                        <enabled>true</enabled>
                      </releases>
                    </repository>
                    <repository>
                      <id>sonatype-nexus-snapshots</id>
                      <url>https://central.sonatype.com/repository/maven-snapshots/</url>
                      <releases>
                        <enabled>false</enabled>
                      </releases>
                      <snapshots>
                        <enabled>true</enabled>
                      </snapshots>
                    </repository>
                  </repositories>
                </profile>
              </profiles>
              <activeProfiles>
                <activeProfile>default</activeProfile>
              </activeProfiles>
            </settings>
            EOF

      - run:
          name: Build project
          command: |
            mvn -s ~/.m2/settings.xml clean install \
              --no-transfer-progress \
              --update-snapshots \
              -DskipTests \
              -Dskip.validation=true \
              -T 2C \
              -Dbundle=dev \
              -P all-modules \
              -DwithJavadoc
          environment:
            BUILD_ID: "circleci-${CIRCLE_BUILD_NUM}"
            BUILD_NUMBER: "${CIRCLE_BUILD_NUM}"

      - save_cache:
          key: maven-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2/repository

      - run:
          name: Display build result
          when: always
          command: |
            if [ $? -eq 0 ]; then
              echo "✅ CircleCI Build completed successfully"
            else
              echo "❌ CircleCI Build failed"
            fi

  validate:
    docker:
      - image: cimg/openjdk:21.0.5
    resource_class: medium
    steps:
      - checkout

      - run:
          name: Validate code style
          command: |
            mvn validate \
              --no-transfer-progress \
              -P all-modules

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - validate
